### ISSUE TITLE
No open source license added in the project 

### ISSUE THREAD

**Issue by chethu** [bogas04/College-Website-Template#3]
Hi 

There is no license in the project, how do i make use of this , can you please provide  appropriate license .

Thanks 
Chethan(chethu002@gmail.com)

**Comment by bogas04** [comment]
My bad.
The project is under MIT license, I'll update it.

**Comment by chethanmandya** [comment]
I appreciate your work, Thanks

**Comment by bogas04** [comment]
Thanks a lot @chethu , don't forget to star the repo! 
Also do let me know if you encounter any issue with the code :)
